### ISSUE TITLE
NoClassDefFoundError / ClassNotFoundException in Quarkus Dev mode using DynamoDB Enhanced Client with @DynamoDbImmutable annotation

### ISSUE THREAD

**Issue by martinrist** [quarkiverse/quarkus-amazon-services#1035]
# Overview

When using the DynamoDB Enhanced Client's `@DynamoDbBean` annotation to map a mutable Java class to a DynamoDB table, everything works as expected, both in Quarkus Dev mode and in production.  Data is returned from DynamoDB and is mapped to the class correctly.

However, when switching over to using an immutable class, with `@DynamoDbImmutable` and a suitable `Builder` implementation, running in Quarkus Dev Mode produces the following stack trace when attempting to access an endpoint that accesses the same table via the immutable class:

```
2023-12-12 12:12:21,111 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /fruits failed, error id: 69b35e37-857e-4bd9-8ee3-14acb2311eac-1: java.lang.NoClassDefFoundError: org/acme/dynamodb/immutable/Fruit
        at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticImmutableTableSchema.constructNewBuilder(StaticImmutableTableSchema.java:597)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticImmutableTableSchema.mapToItem(StaticImmutableTableSchema.java:476)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.StaticImmutableTableSchema.mapToItem(StaticImmutableTableSchema.java:509)
        at software.amazon.awssdk.enhanced.dynamodb.mapper.WrappedTableSchema.mapToItem(WrappedTableSchema.java:57)
        at software.amazon.awssdk.enhanced.dynamodb.internal.EnhancedClientUtils.readAndTransformSingleItem(EnhancedClientUtils.java:105)
        at software.amazon.awssdk.enhanced.dynamodb.internal.EnhancedClientUtils.lambda$readAndTransformPaginatedItems$0(EnhancedClientUtils.java:121)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1708)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at software.amazon.awssdk.enhanced.dynamodb.internal.EnhancedClientUtils.readAndTransformPaginatedItems(EnhancedClientUtils.java:125)
        at software.amazon.awssdk.enhanced.dynamodb.internal.operations.ScanOperation.transformResponse(ScanOperation.java:106)
        at software.amazon.awssdk.enhanced.dynamodb.internal.operations.ScanOperation.transformResponse(ScanOperation.java:38)
        at software.amazon.awssdk.enhanced.dynamodb.internal.operations.PaginatedOperation.lambda$execute$0(PaginatedOperation.java:128)
        at software.amazon.awssdk.enhanced.dynamodb.internal.TransformIterator.next(TransformIterator.java:44)
        at software.amazon.awssdk.core.pagination.sync.PaginatedItemsIterable$ItemsIterator.<init>(PaginatedItemsIterable.java:58)
        at software.amazon.awssdk.core.pagination.sync.PaginatedItemsIterable.iterator(PaginatedItemsIterable.java:48)
        at java.base/java.lang.Iterable.spliterator(Iterable.java:101)
        at software.amazon.awssdk.core.pagination.sync.SdkIterable.stream(SdkIterable.java:34)
        at org.acme.dynamodb.immutable.FruitSyncService.findAll(FruitSyncService.java:27)
        at org.acme.dynamodb.immutable.FruitSyncService_ClientProxy.findAll(Unknown Source)
        at org.acme.dynamodb.immutable.FruitResource.getAll(FruitResource.java:23)
        at org.acme.dynamodb.immutable.FruitResource$quarkusrestinvoker$getAll_b171785799eba31f1048a0d28956079ac26c5674.invoke(Unknown Source)
        at org.jboss.resteasy.reactive.server.handlers.InvocationHandler.handle(InvocationHandler.java:29)
        at io.quarkus.resteasy.reactive.server.runtime.QuarkusResteasyReactiveRequestContext.invokeHandler(QuarkusResteasyReactiveRequestContext.java:141)
        at org.jboss.resteasy.reactive.common.core.AbstractResteasyReactiveContext.run(AbstractResteasyReactiveContext.java:147)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:582)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: org.acme.dynamodb.immutable.Fruit
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:491)
        at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:468)
        ... 36 more
```

Doing the same in a 'production' profile works as expected for both the mutable and immutable class versions.

# Example Repository and Reproduction Steps

Attached to the issue is a minimal sample that illustrates the issue.  This is based on the 'Quarkus Fruits' example application described [here](https://docs.quarkiverse.io/quarkus-amazon-services/dev/amazon-dynamodb.html) - in particular the 'DynamoDB Enhanced Client' section of the guide.

In the example, classes in the `org.acme.dynamodb.mutable` package contain a `MutableFruit` model object, mapped using `@DynamoDbBean`.  When run in Quarkus Dev mode, this exposes an endpoint at http://localhost:8080/mutable-fruits, which behaves as expected.

Classes in the `org.acme.dynamodb.immutable` package have been updated to an immutable class, mapped with `@DynamoDbImmutable` as described in [this AWS post](https://aws.amazon.com/blogs/developer/introducing-immutable-class-mapping-for-the-enhanced-dynamodb-client-in-aws-sdk-for-java-2-x/).  The `Fruit` model class has been made immutable using manually-written Java features.  The same behaviour is observed if getters, and builders are generated using Lombok, or if Java records are used.

When run in Quarkus Dev mode, this exposes an endpoint at http://localhost:8080/fruits.  If the underlying DynamoDB table contains no records, this behaves correctly.  However, if the table contains at least one record, the exception described above is observed.

Full instructions on setting up the example repository, including setting up a local DynamoDB instance with the expected table and records, can be found in the README file in the supplied example.

# Build Details
* Quarkus Version: 3.6.1
* quarkus-amazon-services version: 2.7.2
* Build System: Maven (also experienced with Gradle)
* Java Version: Amazon Coretto 21.0.0.35.1 (same behaviour observed with Coretto 11.0.21 and 17.0.9)

# Sample Project
[quarkus-amazon-services-issue-1035-amazon-dynamodb-quickstart.zip](https://github.com/quarkiverse/quarkus-amazon-services/files/13648140/quarkus-amazon-services-issue-1035-amazon-dynamodb-quickstart.zip)

**Comment by scrocquesel** [comment]
Hello, I've reproduced the bug in dev and test mode. I suspect that the AWS SDK is not using the correct classloader.
I need to delve deeper into the AWS SDK and Quarkus TCCL logic in dev/test mode.

Any assistance would be appreciated.

**Comment by scrocquesel** [comment]
enabling aws sdk debug log didn't produce much information but at least it shows that the TableSchema is cached successfully and it's only when trying to call the builder create method that something fails.

```
quarkus.log.category."software.amazon.awssdk.enhanced.dynamodb.beans".level=DEBUG
```

I also added the classloader name for some classes and it differs

```java
System.out.println(DynamoDBExampleTableEntryImmutable.class.getClassLoader().getName());
System.out.println(DynamoDBExampleTableEntryImmutable.class.getClassLoader().getParent().getName());
System.out.println(TableSchema
        .fromClass(DynamoDBExampleTableEntryImmutable.class).getClass().getClassLoader().getName());
try {
    System.out.println(TableSchema
            .fromClass(DynamoDBExampleTableEntryImmutable.class).getClass().getClassLoader().loadClass(DynamoDBExampleTableEntryImmutable.class.getName()).getName());
} catch (ClassNotFoundException e) {
    e.printStackTrace();
}
```

```plain
Quarkus Runtime ClassLoader: DEV for quarkus-amazon-services-integration-tests-999-SNAPSHOT restart no:2
Quarkus Base Runtime ClassLoader: DEV for quarkus-amazon-services-integration-tests-999-SNAPSHOT
Quarkus Base Runtime ClassLoader: DEV for quarkus-amazon-services-integration-tests-999-SNAPSHOT
java.lang.ClassNotFoundException: io.quarkus.it.amazon.dynamodb.enhanced.DynamoDBExampleTableEntryImmutable
[...]
```

Note that the Base CL is the parent of the first one and only the child CL can load the bean class.

**Comment by martinrist** [comment]
Posting this additional link in here that we discovered whilst initially trying to investigate this issue -> https://github.com/aws/aws-sdk-java-v2/issues/2604.

Although this is an old issue, and refers to the `@DynamoDbBean` version of the mapping (along with `TableSchema.fromBean(...)`), it might throw some light on what's happening.

Comments in that `aws-sdk-java-v2` issue also link to [this issue](https://github.com/quarkusio/quarkus/issues/12168) in the Quarkus repo.  Again, that's an old (now fixed) issue with `@DynamoDbBean` mapping, but might be of use.

**Comment by scrocquesel** [comment]
@martinrist Thanks for the pointer. Some contributors did provide a fix for `DynamoDbBean` in the past to avoid lambda generated code and issue with dev/test mode CL.
https://github.com/quarkiverse/quarkus-amazon-services/blob/main/dynamodb-enhanced/deployment/src/main/java/io/quarkus/amazon/dynamodb/enhanced/deployment/DynamodbEnhancedProcessor.java#L226

We need to replicate the behavior for `DynamoDbImmutable`. As a workaround, if you have a few small entities, you can declare the schema statically.

```java
var schema = StaticImmutableTableSchema
  .builder(DynamoDBExampleTableEntryImmutable.class, DynamoDBExampleTableEntryImmutable.Builder.class)
  .newItemBuilder(DynamoDBExampleTableEntryImmutable::builder,
          DynamoDBExampleTableEntryImmutable.Builder::build)
  .addAttribute(String.class, a -> a.name("key_id")
          .getter(DynamoDBExampleTableEntryImmutable::getKeyId)
          .setter(DynamoDBExampleTableEntryImmutable.Builder::keyId)
          .addTag(primaryPartitionKey()))
  .addAttribute(String.class, a -> a.name("payload")
          .getter(DynamoDBExampleTableEntryImmutable::getPayload)
          .setter(DynamoDBExampleTableEntryImmutable.Builder::payload))
  .addAttribute(String.class, a -> a.name("range_id")
          .getter(DynamoDBExampleTableEntryImmutable::getRangeId)
          .setter(DynamoDBExampleTableEntryImmutable.Builder::rangeId))
  .addAttribute(Instant.class, a -> a.name("created_at_timestamp")
          .getter(DynamoDBExampleTableEntryImmutable::getCreatedAtTimestamp)
          .setter(DynamoDBExampleTableEntryImmutable.Builder::createdAtTimestamp))
  .addAttribute(Instant.class, a -> a.name("updated_at")
          .getter(DynamoDBExampleTableEntryImmutable::getUpdatedAt)
          .setter(DynamoDBExampleTableEntryImmutable.Builder::updatedAt))
  .addAttribute(Long.class, a -> a.name("version")
          .getter(DynamoDBExampleTableEntryImmutable::getVersion)
          .setter(DynamoDBExampleTableEntryImmutable.Builder::version))
  .build();
  
DynamoDbTable<DynamoDBExampleTableEntryImmutable> exampleBlockingTableFromClient = dynamoEnhancedClient.table(
  BLOCKING_TABLE,
  schema);
```

**Comment by martinrist** [comment]
@scrocquesel  - thanks for the update and the workaround suggestion.  I've successfully applied that workaround to the example 'Quarkus Fruits' project posted on the original issue:

```
DynamoDbTable<Fruit> fruitTable = dynamoEnhancedClient.table(FRUIT_TABLE_NAME, buildSchema());

private TableSchema<Fruit> buildSchema() {
    return StaticImmutableTableSchema
        .builder(Fruit.class, Fruit.Builder.class)
        .newItemBuilder(Fruit::builder, Fruit.Builder::build)
        .addAttribute(String.class, a -> a.name("fruitName")
            .getter(Fruit::name)
            .setter(Fruit.Builder::name)
            .addTag(primaryPartitionKey()))
        .addAttribute(String.class, a -> a.name("fruitDescription")
            .getter(Fruit::description)
            .setter(Fruit.Builder::description))
        .build();
}
```

This workaround allows us to convert the `Fruit` model class to a plain Java record, together with Lombok's `@Builder` annotation, which removes duplication between model annotations and the static schema definition:

```
@Builder(builderClassName = "Builder")
public record Fruit(String name, String description) { }
```

**Comment by scrocquesel** [comment]
I made some progress but I'm stuck with the last call to build on the builder to materialize the entity and I guess I'll have to make PR in the AWS sdk repo to be able to hook in their code.

**Comment by scrocquesel** [comment]
@martinrist @cairngorm Can you test the main branch ? Unit tests passed but just want to be sure it works in real stituation before releasing a new version

**Comment by cairngorm** [comment]
@scrocquesel Yes. I should have time to look at this tomorrow.

**Comment by cairngorm** [comment]
@scrocquesel I tested the native build with your fix and it's working as expected. Previously, I had to add `-Dquarkus.native.additional-build-args="--initialize-at-run-time=software.amazon.awssdk.enhanced.dynamodb.internal.mapper.LambdaToMethodBridgeBuilder"` to the native build command. With your fix, that's no longer required.

Thank-you for your time investigating and fixing this issue :smile:

**Comment by martinrist** [comment]
@scrocquesel - @cairngorm & I have tested this update on both the sample project attached to this issue and on the original project we're both working on, and confirm that the `main` branch (as at [commit 3c7758](https://github.com/quarkiverse/quarkus-amazon-services/commit/3c77581b2150b4c32bacae180e84ce293236a7fa)) addresses the issue.

Thanks for all your help on getting this resolved so quickly!

**Comment by scrocquesel** [comment]
I'll prepare the release after work this evening. Thank you for testing and raising this issue

**Comment by scrocquesel** [comment]
[2.7.3](https://github.com/quarkiverse/quarkus-amazon-services/releases/tag/2.7.3) is out
