### ISSUE TITLE
Kinesis support: Unsupported features in 2 methods

### ISSUE THREAD

**Issue by smoell** [quarkiverse/quarkus-amazon-services#1334]
Referencing https://github.com/aws/aws-sdk-java-v2/issues/4803.

Finally had the time to test my pet project with Quarkiverse Kinesis support, but ran into an issue with GraalVM compilation:

```
78.2 Error: Unsupported features in 2 methods
178.2 Detailed message:
178.2 Error: Discovered unresolved field during parsing: software.amazon.awssdk.core.client.config.SdkClientOption.RETRY_STRATEGY. This error is reported at image build time because class software.amazon.awssdk.services.kinesis.DefaultKinesisBaseClientBuilder is registered for linking at image build time by command line and command line.
178.2 Error encountered while parsing software.amazon.awssdk.services.kinesis.DefaultKinesisBaseClientBuilder.finalizeServiceConfiguration(DefaultKinesisBaseClientBuilder.java:80) 
178.2 Parsing context:
178.2    at software.amazon.awssdk.awscore.client.builder.AwsDefaultClientBuilder.finalizeChildConfiguration(AwsDefaultClientBuilder.java:160)
178.2    at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.asyncClientConfiguration(SdkDefaultClientBuilder.java:219)
178.2    at software.amazon.awssdk.services.kinesis.DefaultKinesisAsyncClientBuilder.buildClient(DefaultKinesisAsyncClientBuilder.java:37)
178.2    at software.amazon.awssdk.services.kinesis.DefaultKinesisAsyncClientBuilder.buildClient(DefaultKinesisAsyncClientBuilder.java:25)
178.2    at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:155)
178.2    at io.quarkus.amazon.kinesis.runtime.KinesisAsyncClientProducer.<init>(KinesisAsyncClientProducer.java:17)
178.2    at com.oracle.svm.core.code.FactoryMethodHolder.KinesisAsyncClientProducer_constructor_234a38011d7b0b85015ccb3339616764897433a2(generated:0)
178.2    at static root method.(Unknown Source)
178.2 
178.2 Error: Discovered unresolved method during parsing: software.amazon.awssdk.core.client.config.ClientOverrideConfiguration$Builder.retryMode(). This error is reported at image build time because class software.amazon.awssdk.services.kinesis.DefaultKinesisBaseClientBuilder is registered for linking at image build time by command line and command line.
178.2 Error encountered while parsing software.amazon.awssdk.services.kinesis.DefaultKinesisBaseClientBuilder.invokePlugins(DefaultKinesisBaseClientBuilder.java:149) 
178.2 Parsing context:
178.2    at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.asyncClientConfiguration(SdkDefaultClientBuilder.java:224)
178.2    at software.amazon.awssdk.services.kinesis.DefaultKinesisAsyncClientBuilder.buildClient(DefaultKinesisAsyncClientBuilder.java:37)
178.2    at software.amazon.awssdk.services.kinesis.DefaultKinesisAsyncClientBuilder.buildClient(DefaultKinesisAsyncClientBuilder.java:25)
178.2    at software.amazon.awssdk.core.client.builder.SdkDefaultClientBuilder.build(SdkDefaultClientBuilder.java:155)
178.2    at io.quarkus.amazon.kinesis.runtime.KinesisAsyncClientProducer.<init>(KinesisAsyncClientProducer.java:17)
178.2    at com.oracle.svm.core.code.FactoryMethodHolder.KinesisAsyncClientProducer_constructor_234a38011d7b0b85015ccb3339616764897433a2(generated:0)
178.2    at static root method.(Unknown Source)
```

**Comment by scrocquesel** [comment]
Are you using the aws sdk version from our latest bom or do you override it with a more recent one ?
Comparing with the [integration test](https://github.com/quarkiverse/quarkus-amazon-services/blob/main/integration-tests/src/main/java/io/quarkus/it/amazon/kinesis/KinesisResource.java), do you see anything that could trigger the error ?

**Comment by scrocquesel** [comment]
The latest version now use the jni config from the aws sdk itself. Could you share your pet project or a reproducer ?

**Comment by scrocquesel** [comment]
Closing. If you still have issue, please open a new one with a reproducer.
