### ISSUE TITLE
Upgrade Quarkus quickstarts to 1.5.0

### ISSUE THREAD

**Issue by gsmet** [quarkiverse/quarkus-amazon-services#483]
@scrocquesel wondering if you would be interested in having a look?

It should be done in the `development` branch here: https://github.com/quarkusio/quarkus-quickstarts/tree/development .

I would start with the S3 one as it's the one in which I originally spotted the issue. The idea would be to switch to dev services but I have something suspicious when doing it.

I had a quick try with this diff:

```diff
diff --git a/amazon-s3-quickstart/pom.xml b/amazon-s3-quickstart/pom.xml
index 0eadde56..100a65a9 100644
--- a/amazon-s3-quickstart/pom.xml
+++ b/amazon-s3-quickstart/pom.xml
@@ -16,7 +16,7 @@
         <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
         <maven.compiler.source>11</maven.compiler.source>
         <maven.compiler.target>11</maven.compiler.target>
-        <quarkus-amazon-services.version>1.3.1</quarkus-amazon-services.version>
+        <quarkus-amazon-services.version>1.5.0</quarkus-amazon-services.version>
         <awssdk.testcontainers.version>1.12.57</awssdk.testcontainers.version>
     </properties>
 
diff --git a/amazon-s3-quickstart/src/main/resources/application.properties b/amazon-s3-quickstart/src/main/resources/application.properties
index bf6096ae..739d4c08 100644
--- a/amazon-s3-quickstart/src/main/resources/application.properties
+++ b/amazon-s3-quickstart/src/main/resources/application.properties
@@ -1,5 +1,3 @@
-quarkus.s3.endpoint-override=http://localhost:8008
-
 quarkus.s3.aws.region=us-east-1
 quarkus.s3.aws.credentials.type=static
 quarkus.s3.aws.credentials.static-provider.access-key-id=test-key
diff --git a/amazon-s3-quickstart/src/test/java/org/acme/s3/S3Resource.java b/amazon-s3-quickstart/src/test/java/org/acme/s3/S3Resource.java
deleted file mode 100644
index 298ca454..00000000
--- a/amazon-s3-quickstart/src/test/java/org/acme/s3/S3Resource.java
+++ /dev/null
@@ -1,66 +0,0 @@
-package org.acme.s3;
-
-import java.net.URI;
-import java.util.HashMap;
-import java.util.Map;
-
-import org.testcontainers.DockerClientFactory;
-import org.testcontainers.containers.localstack.LocalStackContainer;
-import org.testcontainers.containers.localstack.LocalStackContainer.EnabledService;
-import org.testcontainers.containers.localstack.LocalStackContainer.Service;
-import org.testcontainers.utility.DockerImageName;
-
-import io.quarkus.test.common.QuarkusTestResourceLifecycleManager;
-import software.amazon.awssdk.auth.credentials.AwsBasicCredentials;
-import software.amazon.awssdk.auth.credentials.StaticCredentialsProvider;
-import software.amazon.awssdk.http.urlconnection.UrlConnectionHttpClient;
-import software.amazon.awssdk.regions.Region;
-import software.amazon.awssdk.services.s3.S3Client;
-
-public class S3Resource implements QuarkusTestResourceLifecycleManager {
-
-    private static final DockerImageName LOCALSTACK_IMAGE_NAME = DockerImageName.parse("localstack/localstack")
-            .withTag("0.12.17");
-    private final static String BUCKET_NAME = "quarkus.test.bucket";
-
-    private LocalStackContainer container;
-    private S3Client client;
-
-    @Override
-    public Map<String, String> start() {
-        DockerClientFactory.instance().client();
-        try {
-            container = new LocalStackContainer(LOCALSTACK_IMAGE_NAME).withServices(Service.S3);
-            container.start();
-
-            URI endpointOverride = container.getEndpointOverride(EnabledService.named(Service.S3.getName()));
-
-            client = S3Client.builder()
-                .endpointOverride(endpointOverride)
-                .credentialsProvider(StaticCredentialsProvider.create(AwsBasicCredentials.create("accesskey", "secretKey")))
-                .httpClientBuilder(UrlConnectionHttpClient.builder())
-                .region(Region.US_EAST_1).build();
-
-            client.createBucket(b -> b.bucket(BUCKET_NAME));
-
-            Map<String, String> properties = new HashMap<>();
-            properties.put("quarkus.s3.endpoint-override", endpointOverride.toString());
-            properties.put("quarkus.s3.aws.region", "us-east-1");
-            properties.put("quarkus.s3.aws.credentials.type", "static");
-            properties.put("quarkus.s3.aws.credentials.static-provider.access-key-id", "accessKey");
-            properties.put("quarkus.s3.aws.credentials.static-provider.secret-access-key", "secretKey");
-            properties.put("bucket.name", BUCKET_NAME);
-
-            return properties;
-        } catch (Exception e) {
-            throw new RuntimeException("Could not start S3 localstack server", e);
-        }
-    }
-
-    @Override
-    public void stop() {
-        if (container != null) {
-            container.close();
-        }
-    }
-}
diff --git a/amazon-s3-quickstart/src/test/java/org/acme/s3/S3ResourcesTest.java b/amazon-s3-quickstart/src/test/java/org/acme/s3/S3ResourcesTest.java
index 95767f93..2f984ae2 100644
--- a/amazon-s3-quickstart/src/test/java/org/acme/s3/S3ResourcesTest.java
+++ b/amazon-s3-quickstart/src/test/java/org/acme/s3/S3ResourcesTest.java
@@ -3,21 +3,20 @@ package org.acme.s3;
 import static io.restassured.RestAssured.given;
 import static org.hamcrest.Matchers.equalTo;
 
-import io.quarkus.test.common.QuarkusTestResource;
-import io.quarkus.test.junit.QuarkusTest;
 import java.io.File;
 import java.io.IOException;
 import java.io.UncheckedIOException;
-import java.nio.charset.StandardCharsets;
 import java.nio.file.Files;
 import java.util.Map;
+
 import javax.ws.rs.core.Response.Status;
-import org.jetbrains.annotations.NotNull;
+
 import org.junit.jupiter.params.ParameterizedTest;
 import org.junit.jupiter.params.provider.ValueSource;
 
+import io.quarkus.test.junit.QuarkusTest;
+
 @QuarkusTest
-@QuarkusTestResource(S3Resource.class)
 public class S3ResourcesTest {
 
     private static final String FILE_NAME_PREFIX = "test-file-";

```

but I end up with the following exception when executing the tests:

```
Caused by: java.lang.NullPointerException: host must not be null.
	at software.amazon.awssdk.utils.Validate.paramNotNull(Validate.java:156)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.<init>(DefaultSdkHttpFullRequest.java:56)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest.<init>(DefaultSdkHttpFullRequest.java:44)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest$Builder.build(DefaultSdkHttpFullRequest.java:482)
	at software.amazon.awssdk.http.DefaultSdkHttpFullRequest$Builder.build(DefaultSdkHttpFullRequest.java:250)
	at software.amazon.awssdk.services.s3.endpoints.internal.AwsEndpointProviderUtils.setUri(AwsEndpointProviderUtils.java:178)
	at software.amazon.awssdk.services.s3.endpoints.internal.S3RequestSetEndpointInterceptor.modifyHttpRequest(S3RequestSetEndpointInterceptor.java:35)
	at software.amazon.awssdk.core.interceptor.ExecutionInterceptorChain.modifyHttpRequestAndHttpContent(ExecutionInterceptorChain.java:90)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.runModifyHttpRequestAndHttpContentInterceptors(BaseClientHandler.java:157)
	at software.amazon.awssdk.core.internal.handler.BaseClientHandler.finalizeSdkHttpFullRequest(BaseClientHandler.java:83)
	at software.amazon.awssdk.core.internal.handler.BaseAsyncClientHandler.doExecute(BaseAsyncClientHandler.java:201)

```

**Comment by scrocquesel** [comment]
test passed with

```
bucket.name=default
```

Now need to figure out why

**Comment by scrocquesel** [comment]
> test passed with
> 
> ```
> bucket.name=default
> ```
> 
> Now need to figure out why

dot in bucket name is the issue. The way the final url is built through aws sdk interceptor is now different and seems it is now confused with an endpoint of <bucket-name>.<host> when host is 127.0.0.1. The new version use S3ResolveEndpointInterceptor and S3RequestSetEndpointInterceptor to build the final URI instance and it has a null host value.

The current quickstart version resolve to http://127.0.0.1:port/<bucketname> instead with EndpointAddressInterceptor using S3EndpointResolverFactory.

I don't know anything about aws sdk, so I will need to dig a bit more the issue.

**Comment by scrocquesel** [comment]
Should have read the doc before reverse engineering the sdk, even if it was quite interesting to read.

Fix the issue by forcing the path style addressing in devservices. S3 seems to be the only one to support this parameter and should be the only one to be affected.
