### ISSUE TITLE
Build-time initialization of TableSchemas broke native-image build.

### ISSUE THREAD

**Issue by knuspertante** [quarkiverse/quarkus-amazon-services#778]
Hey, 

since https://github.com/quarkiverse/quarkus-amazon-services/pull/766 we can generate TableSchema's at build-time and cache them for further usage. This is really nice but if someone (like me ;-)) initialized TableSchema as static (constant) variable (see code snipped below) the native-image fails. 

Error: 
```sh
Caused by: java.lang.IllegalStateException: GraalVM Substitution: Unable to convert Constructor to MethodHandle
	at io.quarkus.amazon.dynamodb.enhanced.runtime.BeanTableSchemaSubstitutionImplementation.newObjectSupplierForClass(BeanTableSchemaSubstitutionImplementation.java:24)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.newObjectSupplierForClass(BeanTableSchema.java)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.createStaticTableSchema(BeanTableSchema.java:189)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.create(BeanTableSchema.java:145)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.lambda$create$0(BeanTableSchema.java:135)
	at java.base/java.util.Map.computeIfAbsent(Map.java:1054)
	at java.base/java.util.Collections$SynchronizedMap.computeIfAbsent(Collections.java:2760)
	at software.amazon.awssdk.enhanced.dynamodb.mapper.BeanTableSchema.create(BeanTableSchema.java:135)
	at software.amazon.awssdk.enhanced.dynamodb.TableSchema.fromBean(TableSchema.java:86)
	at software.amazon.awssdk.enhanced.dynamodb.TableSchema.fromClass(TableSchema.java:140)
	at io.quarkus.amazon.dynamodb.enhanced.runtime.DynamodbEnhancedClientRecorder.createTableSchema(DynamodbEnhancedClientRecorder.java:61)
	at io.quarkus.deployment.steps.DynamodbEnhancedProcessor$recordTableSchema1551640910.deploy_0(Unknown Source)
	at io.quarkus.deployment.steps.DynamodbEnhancedProcessor$recordTableSchema1551640910.deploy(Unknown Source)
```

GraalVM native-image suggest to initialze ApplicationImpl in run-time, but I think this is not a good idea ;-) 
````
com.oracle.svm.core.util.UserError$UserException: Class initialization of io.quarkus.runner.ApplicationImpl failed. Use the option --initialize-at-run-time=io.quarkus.runner.ApplicationImpl
````

```java
@ApplicationScoped
@RegisterForReflection
public class CompanyRepositoryAws implements CompanyRepository {

  private static final TableSchema<CompanyAws> TABLE_SCHEMA =
      TableSchema.fromClass(CompanyAws.class);

  private static final String TABLE_NAME = "Company";

  @Inject DynamoDbEnhancedClient enhancedClient;

  @ConfigProperty(name = "table-suffix")
  String tableSuffix;

  private DynamoDbTable<CompanyAws> mappedTable;

  @PostConstruct
  void init() {
    this.mappedTable = enhancedClient.table(TABLE_NAME + "-" + tableSuffix, TABLE_SCHEMA);
  }
```

The old behavoir could be restored if `quarkus.dynamodbenhanced.create-table-schemas` is set to false.

I mean the new behavoir is nice and has a lot of benefits (not need to use PostConstruct, ...). Therefore this should be the default for "new" projects but we should describe this scenario in docs or handle them if possible? Cause AWS also uses the static initialization in [their example](https://docs.aws.amazon.com/sdk-for-java/latest/developer-guide/ddb-en-client-gs-tableschema.html) 

Is the documentation right?
> Whether a TableSchema should be created at start up classes that has been annotated with **DynamoDb enhanced client annotations** TableSchema are cached and can be retrieved later with TableSchema.fromClass()

or should it be DynamoDbBean?

Please feel free to discuss. For me I will use the "new" way for now.

**Comment by scrocquesel** [comment]
@knuspertante I'm not able to reproduce the issue with this modification in integration tests https://github.com/quarkiverse/quarkus-amazon-services/compare/main...scrocquesel:table-schema?expand=1
I guess something else is conflicting. If you can try to narrow down with a reproducer that would be great

BTW, you can remove `@RegisterForReflection` from your `@DynamoDbBean` annotated classes. And I don't think you need to add `@DynamoDbBean` on `GenericRecord` either.

**Comment by knuspertante** [comment]
Hmmm, you are right! ;-) I found the error and it has nothing todo with the build-time initialization. Sorry for that and thanks for your investigation and effort to this topic! 

> There is two annotations DynamoDbBean and DynamoDbImmutable , I tried to find a short way to explain that but seems not clear. What would you suggest ?

Ah ok, I unterstand your intention, perhaps we can write something like `DynamoDb enhanced client annotations (like @DynamoDbBean or @DynamoDbImmutable)` ? 

Don't get me wrong, we don't need to change anything, that was just my first thought when I read that.

**Comment by scrocquesel** [comment]
@knuspertante Glad you find the issue on your side. I'll merged the modifed integration tests as a showcase with the updated doc.

Aside, thinking about why you need to keep a reference on TableSchema, I'm wondering if something like the below code would help reduce boilerplate code. If so, we could open an issue. I tried to implement https://github.com/quarkiverse/quarkus-amazon-services/issues/176 on top of DynamoDb Enhanced client but translating query while managing indexes and in-memory filter transparently will be a pain. So, maybe reducing boilerplate code could be a good start.

```java
@Path("/dynamodbenhanced")
public class DynamoDbEnhancedResource {

    private final static String BLOCKING_TABLE = "enhancedblocking";

    @Inject
    @TableName(ASYNC_TABLE)
    DynamoDbTable<DynamoDBExampleTableEntry> exampleBlockingTable;

    @GET
    @Path("blocking")
    @Produces(TEXT_PLAIN)
    public String testBlockingDynamo() {
        LOG.info("Testing Blocking Dynamodb client with table: " + BLOCKING_TABLE);

        String partitionKeyAsString = UUID.randomUUID().toString();
        String rangeId = UUID.randomUUID().toString();

        exampleBlockingTable.createTable();

        DynamoDBExampleTableEntry exampleTableEntry = new DynamoDBExampleTableEntry();
        exampleTableEntry.setKeyId(partitionKeyAsString);
        exampleTableEntry.setRangeId(rangeId);
        exampleTableEntry.setPayload(PAYLOAD_VALUE);

        exampleBlockingTable.putItem(exampleTableEntry);

        Key partitionKey = Key.builder().partitionValue(partitionKeyAsString).build();

        DynamoDBExampleTableEntry existingTableEntry = exampleBlockingTable.getItem(partitionKey);

        if (existingTableEntry != null) {
            return existingTableEntry.getPayload() + "@" + existingTableEntry.getVersion();
        } else {
            return "ERROR";
        }
    }
}
```

**Comment by knuspertante** [comment]
Yeah, nice idea! I'm sure this will reduce the amount of boilerplate code.
