### ISSUE TITLE
Devservices fail when docker is not available/supported

### ISSUE THREAD

**Issue by dagrammy** [quarkiverse/quarkus-amazon-services#843]
Sometimes docker is not available or it is not possible to start containers (e.g. CI pipelines in gitlab, localstack might be provided by as a service) 

The documentation https://docs.quarkiverse.io/quarkus-amazon-services/dev/dev-services.html states:

> Dev Services for Amazon Services is automatically enabled for each extensions added to pom.xml except in the following situations:
> 
> - quarkus.devservices.enabled is set to false
> - devservices.enabled is set to false per extension (eg. quarkus.s3.devservices.enabled=false)
> - the endpoint-override is configured (eg. quarkus.s3.endpoint-override=http://localhost:4566)
> - **Your environment does not support Docker**

Reproduce:
Create a project with a quarkus-amazon-services dependency, shutdown docker and run `quarkus dev`.

```
2023-07-17 21:57:02,654 INFO  [io.qua.ama.lam.run.MockEventServer] (build-15) Mock Lambda Event Server Started
2023-07-17 21:57:03,157 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-13) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2023-07-17 21:57:03,424 WARN  [org.tes.doc.DockerClientProviderStrategy] (build-13) DOCKER_HOST unix:///var/run/docker.sock is not listening
2023-07-17 21:57:03,427 WARN  [org.tes.doc.DockerClientProviderStrategy] (build-13) DOCKER_HOST unix:///Users/martin.grammelspacher/.docker/run/docker.sock is not listening
2023-07-17 21:57:03,431 INFO  [org.tes.doc.DockerMachineClientProviderStrategy] (build-13) docker-machine executable was not found on PATH (....)
2023-07-17 21:57:03,432 ERROR [org.tes.doc.DockerClientProviderStrategy] (build-13) Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
As no valid configuration was found, execution cannot continue.
See https://www.testcontainers.org/on_failure.html for more details.
2023-07-17 21:57:04,115 WARN  [io.qua.run.uti.ContainerRuntimeUtil] (build-13) Command "docker info" exited with error code 1. Rootless container runtime detection might not be reliable or the container service is not running at all.
2023-07-17 21:57:04,125 INFO  [org.tes.uti.ImageNameSubstitutor] (build-13) Image name substitution will be performed by: DefaultImageNameSubstitutor (composite of 'ConfigurationFileImageNameSubstitutor' and 'PrefixingImageNameSubstitutor')
2023-07-17 21:57:04,132 INFO  [io.qua.dep.dev.IsolatedDevModeMain] (main) Attempting to start live reload endpoint to recover from previous Quarkus startup failure
2023-07-17 21:57:04,160 ERROR [io.qua.dep.dev.IsolatedDevModeMain] (main) Failed to start quarkus: java.lang.RuntimeException: io.quarkus.builder.BuildException: Build failure: Build failed due to errors
        [error]: Build step io.quarkus.amazon.common.deployment.DevServicesLocalStackProcessor#startLocalStackDevService threw an exception: java.lang.RuntimeException: java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at io.quarkus.amazon.common.deployment.DevServicesLocalStackProcessor.startLocalStack(DevServicesLocalStackProcessor.java:333)
        at io.quarkus.amazon.common.deployment.DevServicesLocalStackProcessor.lambda$startLocalStackDevService$8(DevServicesLocalStackProcessor.java:145)
        at java.base/java.util.HashMap.forEach(HashMap.java:1421)
        at io.quarkus.amazon.common.deployment.DevServicesLocalStackProcessor.startLocalStackDevService(DevServicesLocalStackProcessor.java:144)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at io.quarkus.deployment.ExtensionLoader$3.execute(ExtensionLoader.java:909)
        at io.quarkus.builder.BuildContext.run(BuildContext.java:282)
        at org.jboss.threads.ContextHandler$1.runWith(ContextHandler.java:18)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2513)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1538)
        at java.base/java.lang.Thread.run(Thread.java:833)
        at org.jboss.threads.JBossThread.run(JBossThread.java:501)
Caused by: java.lang.IllegalStateException: Previous attempts to find a Docker environment failed. Will not retry. Please see logs and check configuration
        at org.testcontainers.dockerclient.DockerClientProviderStrategy.getFirstValidStrategy(DockerClientProviderStrategy.java:231)
        at org.testcontainers.DockerClientFactory.getOrInitializeStrategy(DockerClientFactory.java:150)
        at org.testcontainers.DockerClientFactory.getTransportConfig(DockerClientFactory.java:156)
        at org.testcontainers.DockerClientFactory.getRemoteDockerUnixSocketPath(DockerClientFactory.java:171)
        at org.testcontainers.containers.localstack.LocalStackContainer.<init>(LocalStackContainer.java:112)
        at org.testcontainers.containers.localstack.LocalStackContainer.<init>(LocalStackContainer.java:94)
        at io.quarkus.amazon.common.deployment.DevServicesLocalStackProcessor.lambda$startLocalStack$25(DevServicesLocalStackProcessor.java:289)


```
Possible solutions:
- catch the exception, log a warning & startup anyways
- change the doc :sweat_smile:

Yeah, I know...setting `quarkus.devservices.enabled=false` is not a big issue. ^^

But with https://github.com/quarkusio/quarkus/issues/34801 we have to disable each service (which is a little bit noisy)
```
quarkus.s3.devservices.enabled=false
quarkus.sns.devservices.enabled=false
quarkus.sqs.devservices.enabled=false
quarkus.dynamodb.devservices.enabled=false
quarkus.ssm.devservices.enabled=false
```

**Comment by scrocquesel** [comment]
How do you provide the endpoint configuration in your ci pipeline ?

**Comment by scrocquesel** [comment]
I'm in favor of consistency in quarkus ecosystem and for now, AFAIK, all other dev services implementation that require a valid docker env fail if it is not found (and the doc should indeed be changed).

**Comment by dagrammy** [comment]
> How do you provide the endpoint configuration in your ci pipeline ?

Localstack is started as a service within a gitlab CI Job and the endpoint configuration is provided using an env var like `QUARKUS_SNS_ENDPOINT_OVERRIDE=xxx`. 

Also the doc states that dev services are automatically enabled except "the endpoint-override is configured (eg. quarkus.s3.endpoint-override=http://localhost:4566/)". But dev services are started nonetheless.

**Comment by scrocquesel** [comment]
> > How do you provide the endpoint configuration in your ci pipeline ?
> 
> Localstack is started as a service within a gitlab CI Job and the endpoint configuration is provided using an env var like `QUARKUS_SNS_ENDPOINT_OVERRIDE=xxx`.
> 
> Also the doc states that dev services are automatically enabled except "the endpoint-override is configured (eg. quarkus.s3.endpoint-override=http://localhost:4566/)". But dev services are started nonetheless.

Should not be the case, I look into it. I guess, it check only the presence of the 'application.properties'-case name.

**Comment by scrocquesel** [comment]
Are you certain that the environment variables are properly set during test execution ?

I did a test and it behaved as expected.

```sh
$ mvn test
[...]
2023-07-21 23:11:51,839 INFO  [org.tes.doc.DockerClientProviderStrategy] (build-19) Loaded org.testcontainers.dockerclient.UnixSocketClientProviderStrategy from ~/.testcontainers.properties, will try it first
2023-07-21 23:11:51,961 WARN  [org.tes.doc.DockerClientProviderStrategy] (build-19) DOCKER_HOST unix:///var/run/docker.sock is not listening
2023-07-21 23:11:52,039 INFO  [org.tes.doc.DockerMachineClientProviderStrategy] (build-19) docker-machine executable was not found on PATH
2023-07-21 23:11:52,041 ERROR [org.tes.doc.DockerClientProviderStrategy] (build-19) Could not find a valid Docker environment. Please check configuration. Attempted configurations were:
        DockerDesktopClientProviderStrategy: failed with exception NullPointerException (Cannot invoke "java.nio.file.Path.toString()" because the return value of "org.testcontainers.dockerclient.DockerDesktopClientProviderStrategy.getSocketPath()" is null)As no valid configuration was found, execution cannot continue.
See https://www.testcontainers.org/on_failure.html for more details
```
````sh
$ QUARKUS_S3_ENDPOINT_OVERRIDE=http://foo.bar mvn test
[...]
2023-07-21 23:12:07,863 INFO  [io.quarkus] (main) amazon-s3-quickstart 1.0.0-SNAPSHOT on JVM (powered by Quarkus 999-SNAPSHOT) started in 4.074s. Listening on: http://0.0.0.0:8081
2023-07-21 23:12:07,864 INFO  [io.quarkus] (main) Profile test activated. 
2023-07-21 23:12:07,865 INFO  [io.quarkus] (main) Installed features: [amazon-s3, cdi, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, vertx]
2023-07-21 23:12:16,249 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (executor-thread-1) HTTP Request to /s3/upload failed, error id: e8311b40-367c-442a-b0fd-8cf8dcb4da9e-1: software.amazon.awssdk.core.exception.SdkClientException: Unable to load region from any of the providers in the chain software.amazon.awssdk.regions.providers.DefaultAwsRegionProviderChain@6b480ece: [software.amazon.awssdk.regions.providers.SystemSettingsRegionProvider@511a285: Unable to load region from system settings. Region must be specified either via environment variable (AWS_REGION) or  system property (aws.region)., software.amazon.awssdk.regions.providers.AwsProfileRegionProvider@726486e8: No region provided in profile: default, software.amazon.awssdk.regions.providers.InstanceProfileRegionProvider@61f302f4: Unable to contact EC2 metadata service.]

````

**Comment by scrocquesel** [comment]
> Hi @scrocquesel,
> 
> thanks for looking and reproducing.
> 
> You are right, it works if the environment variable is set or an override is specified in the application.properties (eg. `%dev.quarkus.s3.endpoint-override=http://foo.bar` or `%test.quarkus.s3.endpoint-override=http://foo.bar`)
> 
> Unfortunately, there was another problem. :man_facepalming: Sorry for the confusion. 
> 
> If that is the desired and consistent behaviour, then I guess it really should just be the documentation that is adapted.

What should the documentation be ? It seems that it is correct regarding my tests and yours.

**Comment by dagrammy** [comment]
I was referring to the original reason for this issue.

> Dev Services for Amazon Services is automatically enabled for each extensions added to pom.xml except in the following situations:
> 
> - quarkus.devservices.enabled is set to false
> - devservices.enabled is set to false per extension (eg. quarkus.s3.devservices.enabled=false)
> - the endpoint-override is configured (eg. quarkus.s3.endpoint-override=http://localhost:4566)
> - ~~Your environment does not support Docker~~

**Comment by scrocquesel** [comment]
> I was referring to the original reason for this issue.
> 
> > Dev Services for Amazon Services is automatically enabled for each extensions added to pom.xml except in the following situations:
> > 
> > * quarkus.devservices.enabled is set to false
> > * devservices.enabled is set to false per extension (eg. quarkus.s3.devservices.enabled=false)
> > * the endpoint-override is configured (eg. quarkus.s3.endpoint-override=http://localhost:4566)
> > * ~Your environment does not support Docker~

Ah yes, in testing mode, it will fail if the application is not configured properly and dev services cannot start to offer its configuration. There is no point to test an application that is not properly configured as tests should fails anyway.
